### ISSUE TITLE
AI not prioritizing researching nanotechnology when going for science victory

### ISSUE THREAD

**Issue by Phyrax1** [Infixo/Civ6-Real-Strategy#24]
Countless times I have experienced the AI already having researched smart materials and clearly wanting to go for a science victory but not researching nanotechnology for some reason. Eventually they will research it and sometimes they research it fast, but it can vary by a lot (sometimes they even researched future tech multiple times before finally deciding to go for it). 
That's why they get stuck at this victory step so often. I know you've already added the tech to favored science victory techs, but it just doesn't work.

**Comment by Phyrax1** [comment]
Also, Offworld Mission and Smart Materials are not in ScienceVictoryTechs. Just in case you weren't aware.

**Comment by Infixo** [comment]
Nanotechnology is a Favored tech. I don't know what else can be done here, seems like it needs engine fix.
